### ISSUE TITLE
Unintended error when querying user that does not exist

### ISSUE THREAD

**Issue by drewdorris** [Ruinscraft/ruinscraft-punishments#3]
https://github.com/Ruinscraft/ruinscraft-punishments/blob/master/plugin/src/main/java/com/ruinscraft/punishments/commands/QueryPunishmentCommand.java#L33
> [02:10:22 WARN]: java.lang.IllegalArgumentException: UUID cannot be null
[02:10:22 WARN]:        at org.apache.commons.lang.Validate.notNull(Validate.java:192)
[02:10:22 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.getOfflinePlayer(CraftServer.java:1486)
[02:10:22 WARN]:        at org.bukkit.Bukkit.getOfflinePlayer(Bukkit.java:848)
[02:10:22 WARN]:        at com.ruinscraft.punishments.PlayerLookups.lambda$getName$0(PlayerLookups.java:23)
[02:10:22 WARN]:        at com.ruinscraft.punishments.commands.QueryPunishmentCommand.lambda$lookup$0(QueryPunishmentCommand.java:33)
[02:10:22 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84)
[02:10:22 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[02:10:22 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[02:10:22 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[02:10:22 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[02:10:22 WARN]:        at java.lang.Thread.run(Thread.java:748)

**Comment by ds58** [comment]
Forgot to remove a printStackTrace(). It was a try-catch that was supposed to return on caught exception
